objective:
    - Lasso Regression[fit_intercept=False,reg=0.1]
    - Lasso Regression[fit_intercept=False,reg=0.01]
    - Lasso Regression[fit_intercept=False,reg=0.001]
dataset:
    - finance
n-repetitions: 5
n-jobs: 7
timeout: 6000
solver:
  - blitz
  - cd
  - celer
  - cuml
  - glmnet
  - lars
  - sklearn
  - modopt-fista
  - python-pgd
  - skglm
  - snapml
  - noncvx-pro